### ISSUE TITLE
Upgrade to Dremio ver. 20+

### ISSUE THREAD

**Issue by hmelnoff** [mmsmdali/dremio-clickhouse-arp-connector#2]
Hello, mmsmdali. First of all I want to thank you for the great job! But unfortunately I met issues with compiling application for using it with Dremio 20.1.0. Could you please tell me if you have some plans to update the code and to add compatibility with newer versions of Dremio? And if no, could you please tell me if there are some difficulties in such job so I could ask developers in our company to continue develop your application.

Thank you and have a nice day!

**Comment by mmsmdali** [comment]
Hi I worked out the changes for Dremio 20.1.0 against [official ClickHouse JDBC driver](https://github.com/altxcorp/clickhouse-jdbc). Its working fine. Will push the changes after complete testing.

**Comment by mmsmdali** [comment]
Hi now it works with latest [Dremio 20.1.0](https://github.com/dremio/dremio-oss) & connects latest [ClickHouse v22.3.3.44-lts](https://github.com/ClickHouse/ClickHouse) through latest [official ClickHouse JDBC driver v0.3.2-patch8](https://github.com/ClickHouse/clickhouse-jdbc) in Linux Environment.
